### ISSUE TITLE
add third talk

### ISSUE THREAD

**Issue by jhamman** [jhamman/UW_Python_for_Geosciences#2]
@jakevdp - Thanks for giving the Geoscience Python talk this week.  If you are looking for a place to post the slides and/or ipython notebook, you can drop them here for now.

**Comment by jakevdp** [comment]
Cool – how would you like me to do that? I have PDF of slides and the IPython notebook I used. Should I submit a PR to this repo?

**Comment by jhamman** [comment]
Yeah, that works.  At some point I'll put together a more formal website but for now, that's how we're doing things.  Thanks.

**Comment by jakevdp** [comment]
Great. Done in https://github.com/jhamman/UW_Python_for_Geosciences/pull/3
