### ISSUE TITLE
Add 4th talk (Charles Maalouf)

### ISSUE THREAD

**Issue by lizaclark** [jhamman/UW_Python_for_Geosciences#4]
@jhamman  @emiliom : I'm trying out siphon right now and wishing I could reference Charles Maalouf's ipython notebook from last week. Could one of you please share his email address with me so that I can request it? and/or ask him to post it here? My email is eclark2@uw.edu.

**Comment by emiliom** [comment]
Hi @lizaclark. I just sent Charlie a reminder to send me his presentation materials (slides and ipython notebook). He definitely intended to do that. I'll post it on the seminar repo once I get it from him.

I'll send you his email address via email.

**Comment by lizaclark** [comment]
He actually just sent me the materials. (I asked around until I found
someone with his email). I told him I'd put the PR in with github, which
I'll do now.

**Comment by emiliom** [comment]
Fantastic, thank you! I'll followup with him to tell him to ignore my email. I'll merge your PR when it arrives.
